name:                servantAPI
version:             0.1.0.0
github:              "githubuser/servantAPI"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/servantAPI#readme>

dependencies:
- base >= 4.7 && < 5
- servant-server
- time
- text
- servant
- blaze-html
- aeson
- blaze-markup
- directory
- warp
- wai
- http-media
- lucid
- string-conversions
- bytestring
- attoparsec
- mtl
- base-compat-batteries

default-extensions:
- DeriveGeneric
- DataKinds 
- DeriveGeneric
- FlexibleInstances
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- OverloadedStrings
- RankNTypes
- ScopedTypeVariables
- TypeOperators
- ExplicitNamespaces

library:
  source-dirs: src

executables:
  servantAPI-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servantAPI

tests:
  servantAPI-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servantAPI
